## Day 2 Task *Numpy*

In [27]:
import numpy as np

In [28]:
print("Helo World")

Helo World


In [29]:
myarr = np.array([[3,5,6,7,8]], np.int64)

In [30]:
myarr

array([[3, 5, 6, 7, 8]])

In [31]:
myarr[0, 1]

np.int64(5)

In [32]:
myarr.dtype

dtype('int64')

In [33]:
myarr.shape

(1, 5)

In [34]:
myarr[0, 1] = 56

In [35]:
myarr

array([[ 3, 56,  6,  7,  8]])

In [36]:
print(myarr)

[[ 3 56  6  7  8]]


# conversion from other structure

In [37]:
list =np.array([[1,2,3],[5,6,7],[8,9,0]])

In [38]:
list

array([[1, 2, 3],
       [5, 6, 7],
       [8, 9, 0]])

In [39]:
list.size

9

In [40]:
list.dtype

dtype('int64')

In [43]:
list.shape

(3, 3)

In [53]:
zeros = np.zeros((2, 7))
zeros

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [55]:
rng = np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [58]:
emp = np.empty((2, 4))
emp

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [63]:
ide = np.identity(5)
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [66]:
ide.shape

(5, 5)

In [67]:
ide.size

25

In [69]:
arr = np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [76]:
arr.reshape(3, 33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [77]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [79]:
x = [[1,2,3],[4,5,6],[7,8,9]]
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
ar.sum(axis=0)

array([12, 15, 18])

In [82]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])